# Generated by Django 4.0.8 on 2023-01-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('client_name', models.CharField(max_length=255)),
                ('client_dni', models.IntegerField()),
                ('price', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('CC', 'credit_card'), ('C', 'cash'), ('T', 'transfer')], default='CC', max_length=255)),
                ('status_code', models.CharField(choices=[('Pe', 'pending'), ('Pa', 'payed'), ('De', 'deleted')], default='Pe', max_length=255)),
            ],
        ),
    ]
