# Generated by Django 4.0.8 on 2023-01-19 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_guests', models.PositiveIntegerField()),
                ('price_per_night', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('client_name', models.CharField(max_length=255)),
                ('client_identity_card', models.PositiveIntegerField()),
                ('client_email', models.EmailField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('CC', 'Credit_card'), ('CA', 'Cash'), ('TR', 'Transfer')], default='CC', max_length=255)),
                ('status_code', models.CharField(choices=[('PE', 'Pending'), ('PA', 'Payed'), ('DE', 'Deleted')], default='Pe', max_length=255)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.room')),
            ],
        ),
    ]
