# Generated by Django 4.0.8 on 2023-01-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status_code',
            field=models.CharField(choices=[('PE', 'Pending'), ('PA', 'Paid'), ('DE', 'Deleted')], default='PE', max_length=255),
        ),
    ]
